const CAPA_DB = {
  "rfg": [
    {
      "month": "Nov 2025",
      "pm": 1.5,
      "pt": 1,
      "assy": 3.5,
      "test": 3,
      "tb": 3,
      "total": 9,
      "cap_mon": 67.8,
      "cap_year": 813,
      "note": "생산관리자 : 유주영 0.5, 권용일 0.5, 시몬 0.5 생산기술자 강지승, 테스터 : 빈, 유준, 루안"
    },
    {
      "month": "Dec 2025",
      "pm": 1.5,
      "pt": 1,
      "assy": 3.5,
      "test": 3,
      "tb": 3,
      "total": 9,
      "cap_mon": 67.8,
      "cap_year": 813,
      "note": "생산관리자 : 유주영 0.5, 권용일 0.5, 시몬 0.5 생산기술자 강지승, 테스터 : 빈, 유준, 루안"
    },
    {
      "month": "Jan 2026",
      "pm": 1.5,
      "pt": 1,
      "assy": 3.5,
      "test": 3,
      "tb": 3,
      "total": 9,
      "cap_mon": 67.8,
      "cap_year": 813,
      "note": "생산관리자 : 유주영 0.5, 권용일 0.5, 시몬 0.5 생산기술자 강지승, 테스터 : 빈, 유준, 루안"
    },
    {
      "month": "Feb 2026",
      "pm": 0,
      "pt": 0,
      "assy": 0,
      "test": 0,
      "tb": 0,
      "total": 0,
      "cap_mon": 0,
      "cap_year": 0,
      "note": ""
    },
    {
      "month": "Mar 2026",
      "pm": 0,
      "pt": 0,
      "assy": 0,
      "test": 0,
      "tb": 0,
      "total": 0,
      "cap_mon": 0,
      "cap_year": 0,
      "note": ""
    },
    {
      "month": "Apr 2026",
      "pm": 0,
      "pt": 0,
      "assy": 0,
      "test": 0,
      "tb": 0,
      "total": 0,
      "cap_mon": 0,
      "cap_year": 0,
      "note": ""
    },
    {
      "month": "May 2026",
      "pm": 0,
      "pt": 0,
      "assy": 0,
      "test": 0,
      "tb": 0,
      "total": 0,
      "cap_mon": 0,
      "cap_year": 0,
      "note": ""
    }
  ],
  "rfm": [
    {
      "month": "Nov 2025",
      "pm": 1,
      "pt": 1,
      "assy": 4.5,
      "test": 2.5,
      "tb": 3,
      "total": 9,
      "cap_mon": 99.8,
      "cap_year": 1009,
      "note": "신입테스터 교육 (0.5)"
    },
    {
      "month": "Dec 2025",
      "pm": 1,
      "pt": 1,
      "assy": 4.5,
      "test": 3,
      "tb": 3,
      "total": 9.5,
      "cap_mon": 99.8,
      "cap_year": 1198,
      "note": "생산관리자 : 유주영 0.5, 장미숙 0.5 생산기술자 : 이루리"
    },
    {
      "month": "Jan 2026",
      "pm": 1,
      "pt": 1,
      "assy": 4.5,
      "test": 3,
      "tb": 3,
      "total": 9.5,
      "cap_mon": 99.8,
      "cap_year": 1198,
      "note": "생산관리자 : 유주영 0.5, 장미숙 0.5 생산기술자 : 이루리"
    },
    {
      "month": "Feb 2026",
      "pm": 0,
      "pt": 0,
      "assy": 0,
      "test": 0,
      "tb": 0,
      "total": 0,
      "cap_mon": 0,
      "cap_year": 0,
      "note": ""
    },
    {
      "month": "Mar 2026",
      "pm": 0,
      "pt": 0,
      "assy": 0,
      "test": 0,
      "tb": 0,
      "total": 0,
      "cap_mon": 0,
      "cap_year": 0,
      "note": ""
    },
    {
      "month": "Apr 2026",
      "pm": 0,
      "pt": 0,
      "assy": 0,
      "test": 0,
      "tb": 0,
      "total": 0,
      "cap_mon": 0,
      "cap_year": 0,
      "note": ""
    },
    {
      "month": "May 2026",
      "pm": 0,
      "pt": 0,
      "assy": 0,
      "test": 0,
      "tb": 0,
      "total": 0,
      "cap_mon": 0,
      "cap_year": 0,
      "note": ""
    }
  ],
  "evc": [
    {
      "month": "Nov 2025",
      "pm": 2.5,
      "pt": 2,
      "assy": 4,
      "test": 4,
      "tb": 6,
      "total": 12.5,
      "cap_mon": 48,
      "cap_year": 514,
      "note": "생산관리자 :  권용일 0.5, 박범준, 조재영, 테스트벤치 tykon 3, quantum 3"
    },
    {
      "month": "Dec 2025",
      "pm": 2.5,
      "pt": 2,
      "assy": 4,
      "test": 4,
      "tb": 6,
      "total": 12.5,
      "cap_mon": 48,
      "cap_year": 514,
      "note": "생산관리자 :  권용일 0.5, 박범준, 조재영, 테스트벤치 tykon 3, quantum 3"
    },
    {
      "month": "Jan 2026",
      "pm": 2.5,
      "pt": 2,
      "assy": 4,
      "test": 4,
      "tb": 6,
      "total": 12.5,
      "cap_mon": 48,
      "cap_year": 514,
      "note": "생산관리자 :  권용일 0.5, 박범준, 조재영, 테스트벤치 tykon 3, quantum 3"
    },
    {
      "month": "Feb 2026",
      "pm": 0,
      "pt": 0,
      "assy": 0,
      "test": 0,
      "tb": 0,
      "total": 0,
      "cap_mon": 0,
      "cap_year": 0,
      "note": ""
    },
    {
      "month": "Mar 2026",
      "pm": 0,
      "pt": 0,
      "assy": 0,
      "test": 0,
      "tb": 0,
      "total": 0,
      "cap_mon": 0,
      "cap_year": 0,
      "note": ""
    },
    {
      "month": "Apr 2026",
      "pm": 0,
      "pt": 0,
      "assy": 0,
      "test": 0,
      "tb": 0,
      "total": 0,
      "cap_mon": 0,
      "cap_year": 0,
      "note": ""
    },
    {
      "month": "May 2026",
      "pm": 0,
      "pt": 0,
      "assy": 0,
      "test": 0,
      "tb": 0,
      "total": 0,
      "cap_mon": 0,
      "cap_year": 0,
      "note": ""
    }
  ]
};